### ISSUE TITLE
Get size of text before rendering.

### ISSUE THREAD

**Issue by scripturial** [jeffersoncbd/image-builder#1]
This library is a nice quick way to build som simple images. One problem I am having is working out where to draw text. I'd like to be able to do something like Text.rect() to get the pixel width and height that the text rectangle would would consume. This would allow doing something like

``` rs
    let picture_width = 1000
    let picture_centre = picture_width / 2  // Calculate centre of image

    // Draw text string in "centre" of the image.
    let text_x = picture_centre - (text_width / 2);
```

**Comment by jeffersoncbd** [comment]
Sorry for the delay in responding; my email inbox got out of control, and I ended up missing the notification. This is a real issue with this library because it’s complex to define the size that a text will occupy, as the letters will have different widths and heights depending on the font the user chooses. I did find some solutions to this problem, but they were too complex and could make this part more low-level for the library user (which goes against its purpose). However, if you have any suggestions on how to solve this problem, I’d be happy to try them.

**Comment by scripturial** [comment]
I can see you merged my pull request. It adds a `text_size()` method to the main `Image` which I am using to calculate the size of a string before I add the text to the image, so it now works a bit like this:

``` rs
    // Demonstrate how to centre a text string.

    // Create the Text object, and measure it's width
    let t = Text::new(&text)
            .size((self.height as f64 * height) as u32)
            .font("HelveticaNeue")
            .color([255, 255, 255, 255]);
    let (text_width, _) = image.borrow_mut().text_size(&t);
    
    // Calculate centre of image.
    let picture_width = 1000
    let picture_centre = picture_width / 2  // Calculate centre of image

    // Draw text string in "centre" of the image.
    let text_x = picture_centre - (text_width / 2);
```
